### ISSUE TITLE
Subscription via gateway

### ISSUE THREAD

**Issue by ZirgVoice** [d-exclaimation/pioneer#134]
The apollo gateway doesn't work with subscriptions, that's why I was looking for alternatives. All alternatives I found in `Sec-WebSocket-Protocol` send `"graphql-ws, graphql-transport-ws"`. Could you add a handling for this? Right now I'm getting a 400 error when subscribing through the gateway.

**Comment by d-exclaimation** [comment]
It would be pretty easy to allow the client to sent both protocol headers and the server only performing based on what protocol it is configured with

It would be a bigger change to support both protocol at the same time on the server

**Comment by d-exclaimation** [comment]
I can get the first done by tomorrow. A bit busy right now

**Comment by d-exclaimation** [comment]
Should be in `v.1.3.1`
