### ISSUE TITLE
Value null in data on errors

### ISSUE THREAD

**Issue by ZirgVoice** [d-exclaimation/pioneer#137]
**Is your feature request related to a problem? Please describe.**
Some gateways have problems decoding errors. The gateway cannot decode an error when it receives an error without a `data` field.

**Describe the solution you'd like**
In case of errors, the `data` field can be set to `null`

**Additional context**
I'm not sure if this should be done in `pioneer`, perhaps it would be better done in `GraphQL` or `Graphiti`. But I found in `pioneer` that the `data` field is set to `nil` on errors, so the response that the gateway gets does not contain this field.

**Comment by d-exclaimation** [comment]
So on errors with no data, the `data` property in the JSON response should always be set to `null` or is it the other around?

In either case, GraphQLResult is part of [GraphQL](https://github.com/GraphQLSwift/GraphQL) so it probably need to be implemented there, but I can probably make a PR for this.

**Comment by ZirgVoice** [comment]
Yes, that's right.

**Comment by d-exclaimation** [comment]
Can I ask what gateway are you using?

I checked what `data` property should be with the GraphQL spec laid out [here](https://spec.graphql.org/October2021/#sec-Data). The present of the `data` property must not exist if the error comes before the execution but must exist after, so it may or may not exist in the response depending on the scenario. It wouldn't make sense to change the implementation to have `data` property to always be `null` and not follow the spec here. 

I can instead fix the GraphQLResult type to have a way to explicitly specify where to have `data` as null or excluded, but I am not sure this would fix the issue with the gateway not recognising errors if the `data` is excluded in the response.

Or, would it make more sense have option in Pioneer to go out of the spec and have `data` should always be included if really necessary?

**Comment by ZirgVoice** [comment]
I've been looking for a long time for a gateway that works with subscriptions. I settled on this https://github.com/K0R0VA/apollo-gateway-rs. Its data field is not optional. I know Apollo Router supports subscription now, but they have this feature as part of their Enterprise plan.

**Comment by ZirgVoice** [comment]
At the moment I use Middleware to pass null in the data field in case of error, but to do that I have to decode each response in GraphQLResult, it really slows down the work, especially when the response has a lot of data.

**Comment by d-exclaimation** [comment]
Hmm, I see. Honestly, I am unsure about making the decision to change the `data` property at Pioneer's level. 

I think opening an issue about this in [GraphQL](https://github.com/GraphQLSwift/GraphQL) would be best and letting GraphQLSwift maintainers decide on how to resolve this issue.

I would also open an issue on [apollo-gateway-rs](https://github.com/K0R0VA/apollo-gateway-rs) about this, I am bit confused on why they doesn't accept `data` as optional field.

**Comment by ZirgVoice** [comment]
It would be nice to have a subscription-supported gateway in the Swift language🙂

**Comment by ZirgVoice** [comment]
I then close this issue. I will make an issue in apollo-gateway-rs on the implementation of the optional data field
