### ISSUE TITLE
Set some to the response

### ISSUE THREAD

**Issue by ZirgVoice** [d-exclaimation/pioneer#29]
How can I add something to the response? For example, I need to add cookies

**Comment by d-exclaimation** [comment]
The Vapor request and response object are given as parameter to the context builder in the `Pioneer` initiator ([more details here](https://pioneer-graphql.netlify.app/references/pioneer/#init)). You can use that to create a `Context` struct that contains the request specific response ([An example of context builder](https://pioneer-graphql.netlify.app/guides/getting-started/server/#integration))

From there you can grab the context from the resolver as its first parameter.

**Comment by d-exclaimation** [comment]
It should look and work similarly to `apollo-server-express`

**Comment by ZirgVoice** [comment]
I did that, but how do I add cookies for example in the response of the [Users](https://pioneer-graphql.netlify.app/guides/getting-started/resolver/#resolver) function?

**Comment by d-exclaimation** [comment]
The `Response` object should have the `cookies` property ([`Response`'s cookie](https://api.vapor.codes/vapor/main/Vapor/Response/#response.cookies)). You can just add the cookie manually by mutating that `cookies` if I am not mistaken ([`HTTPCookies` object have subscript method that handle setting values](https://github.com/vapor/vapor/blob/21dde333cac46d99c3f25bc5fe2d9e5ea708cb7b/Sources/Vapor/HTTP/Headers/HTTPCookies.swift#L286))

**Comment by ZirgVoice** [comment]
I know how to add cookies to the response. Explain how I can add cookies to the response that is in the context of the users function. In the users function, I return the type [User] and not Response

**Comment by ZirgVoice** [comment]
in this case, the function createCookies returns a response with a cookie
<img width="884" alt="Bildschirmfoto 2022-05-18 um 19 39 02" src="https://user-images.githubusercontent.com/50185064/169107196-dab71738-e5e4-4ec7-8bb4-e735ead94fe4.png">

**Comment by d-exclaimation** [comment]
You can't reassigned the response object with your own. You have to use the response given

**Comment by ZirgVoice** [comment]
Thank you very much, everything is clear now
