### ISSUE TITLE
Error load fields

### ISSUE THREAD

**Issue by ZirgVoice** [d-exclaimation/pioneer#30]
When I try to get the parent id, I get an error "Fatal error: Cannot access field before it is initialized or fetched: country_id".
I found that all fields are empty except id

```swift
extension AddressModel {
    func getCountry(context: Context, _: NoArguments, eventLoopGroup: EventLoopGroup) async throws -> CountryModel? {
        let id = self.$country.id
        return try await context.request.graphQLDataLoader
            .countryLoader.load(key: id, on: eventLoopGroup).get()
    }
}
```

**Comment by ZirgVoice** [comment]
This is Parent and not OptionalParent. The country_id field in the database is full. I don’t do join and with because I just need to get the parent’s id, I also tried to get here and other fields, for example zip_code, this field is also filled in the database but comes empty. As a result, I can only get the id. I used [this library](https://github.com/alexsteinerde/graphql-kit) before and getting the parent id worked.

**Comment by d-exclaimation** [comment]
Can you share more about the AddressModel and the schema as well? I'll look into it and figure out why this is could be happening.

**Comment by ZirgVoice** [comment]
This happens with any model, not just the AddressModel. Here's what the AddressModel looks like:

```swift
final class AddressModel: Model {
    static let schema = "addresses"

    @ID(key: .id)
    var id: UUID?

    @Field(key: .address)
    var address: String

    @Field(key: .zipCode)
    var zipCode: String

    @Field(key: .city)
    var city: String

    @OptionalField(key: .longitude)
    var longitude: Double?

    @OptionalField(key: .latitude)
    var latitude: Double?

    @Parent(key: .countryID)
    var country: CountryModel

    @Timestamp(key: .createdAt, on: .create)
    var createdAt: Date?

    @Timestamp(key: .updatedAt, on: .update)
    var updatedAt: Date?

    @Timestamp(key: .deletedAt, on: .delete)
    var deletedAt: Date?

    init() {}

    init(
        address: String,
        zipCode: String,
        city: String,
        longitude: Double?,
        latitude: Double?,
        countryID: CountryModel.IDValue
    ) {
        self.address = address
        self.zipCode = zipCode
        self.city = city
        self.longitude = longitude
        self.latitude = latitude
        self.$country.id = countryID
    }

    init(_ arguments: CreateAddressArguments) {
        self.id = UUID()
        self.address = arguments.address
        self.zipCode = arguments.zipCode
        self.city = arguments.city
        self.longitude = arguments.longitude
        self.latitude = arguments.latitude
        self.$country.id = arguments.countryID
    }
}
```
In the schema, the type looks like this:
```swift
    Type(AddressModel.self) {
        Field("id", at: \.id)
        Field("address", at: \.address)
        Field("zipCode", at: \.zipCode)
        Field("city", at: \.city)
        Field("longitude", at: \.longitude)
        Field("latitude", at: \.latitude)
        Field("country", at: AddressModel.getCountry, as: TypeReference<CountryModel>.self)
        Field("createdAt", at: \.createdAt)
        Field("updatedAt", at: \.updatedAt)
    }
```

**Comment by d-exclaimation** [comment]
I couldn't reproduce the issue. 

I tried getting the `Parent` relation (getting the parent's `id`) and make a similar models worked fine as long as its correct in the database.

Here is the code I used
<details>
<summary>Model classes</summary>

```swift
final class User: Model, Content {
    static var schema: String = "users"
    
    @ID(key: .id)
    var id: UUID?
    
    @Field(key: "name")
    var name: String

    init() { }
    
    init(id: UUID? = nil, name: String) {
        self.id = id
        self.name = name
    }
}

final class Item: Model, Content {
    static let schema = "items"

    @ID(key: .id)
    var id: UUID?

    @Field(key: "name")
    var name: String

    @Parent(key: "user_id")
    var user: User
    
    init() { }

    init(id: UUID? = nil, name: String, userID: UUID) {
        self.id = id
        self.name = name
        self.$user.id = userID
    }
}
```

</details>

```swift
extension Item {
    func owner(ctx: Context, _: NoArguments) async throws -> User? {
        // I receive no fatal error here
        print("\(self.$user.id)")
        // No fatal error here either
        return try await User.query(on: ctx.req.db).filter(\.$id == $user.id).first()
    }
}
        
Type(Item.self) {
    Field("name", at: \.name)
    Field("owner", at: Item.owner, as: TypeReference<User>.self)
}
```

Can share how do you fetch the `AddressModel` itself (the Query / Mutation resolver) before the `getCountry` method was called?

**Comment by ZirgVoice** [comment]
Resolver
```swift
    func getAddress(
        context: Context,
        arguments: IDArgument
    ) async throws -> AddressModel {
        guard
            let model = try await AddressModel.query(on: context.request.db)
            .filter(\.$id == arguments.id)
            .first()
        else {
            throw Abort(.notFound, reason: "Address with id \(arguments.id) not found")
        }
        return model
    }
```
Schema
```swift
    Query {
        Field("getAddress", at: GraphQLResolver.getAddress) {
            Argument("id", at: \.id)
        }
    }
```

**Comment by ZirgVoice** [comment]
Country field is empty
<img width="1728" alt="Bildschirmfoto 2022-05-19 um 12 34 27" src="https://user-images.githubusercontent.com/50185064/169274106-fb536c97-2ea2-47c5-9343-3b52136b9bf7.png">

**Comment by d-exclaimation** [comment]
I'll try to look into it more to find what went wrong here. 

Honestly, I am not sure why is this happening. My test code also uses PostgreSQL but mine worked. There is nothing out of the ordinary with the code you shared, so it should work fine. The only notable thing is that your model is  `@Parent(key: .countryID)` instead of `@Parent(key: "country_id")`, but if that part compiles, it shouldn't break all of the sudden.

I'll also share my migrations code used to build the tables for my test code, just in case you manage to find the problem from it

```swift
struct CreateUser: AsyncMigration {
    func prepare(on database: Database) async throws {
        try await database.schema("users")
            .id()
            .field("name", .string)
            .create()
    }

    func revert(on database: Database) async throws {
        try await database.schema("users").delete()
    }
}

struct CreateItem: AsyncMigration {
    func prepare(on database: Database) async throws {
        try await database.schema("items")
            .id()
            .field("name", .string)
            .field("user_id", .uuid, .references("users", "id"))
            .create()
    }

    func revert(on database: Database) async throws {
        try await database.schema("items").delete()
    }
}
```

**Comment by ZirgVoice** [comment]
I found what the problem is, I wrote a parser for the fields that come in the request to get from the database only those fields that were requested, and there was no country field in it. This parser is more like a crutch. Perhaps you know if there is a way to get the list of requested fields in Graphiti?

**Comment by d-exclaimation** [comment]
It's good to know that you figured out why the bug is happening. I don't think you can get it from `Graphiti` directly but you could probably grab those requested fields from the `Request` object, probably by parsing the request into `GraphQLRequest`. 

From that you can access the `source` and using the [GraphQLSwift/GraphQL](https://github.com/GraphQLSwift/GraphQL) `parse` method to get the `Document` and manually find the field being requested from `OperationDefinition`.

You will have to go low level into the [GraphQLSwift/GraphQL](https://github.com/GraphQLSwift/GraphQL) library.

You'll ended up doing something like this.
```swift
let gql = try ctx.req.content.decode(GraphQLRequest.self)
let fieldsRequested = try parse(source: Source(body: gql.query))
    .definitions
    .flatMap { def -> [Selection] in
        guard let op = def as? OperationDefinition else {
            return []
        }
        return op.selectionSet.selections
    }
    .compactMap { selection -> Field? in
        guard let field = selection as? Field else {
            return nil
        }
        return field
    }
```

**Comment by ZirgVoice** [comment]
Thanks for the help!
