### ISSUE TITLE
Should the context builder be allowed to throw an error?

### ISSUE THREAD

**Issue by cshadek** [d-exclaimation/pioneer#36]
One common example I could see is if the context requires verifying and decoding a JWT access token or if before the context is created a query needs to be made to a database and if the user doesn't exist it should throw an error.

To my knowledge this is not possible right now.

I think it's a relatively simple change in the ```handle``` function in Pioneer.swift.  The context would just have to be created before executeGraphQL.

**Comment by d-exclaimation** [comment]
It is a simple change, I haven't implemented yet since I thought for the most part you can move that portion of the code into the resolver, so it's not urgent.

**Comment by d-exclaimation** [comment]
I'll probably start implementing that change soon. It would also make sense to make the context builder an async throwing function

**Comment by cshadek** [comment]
I don't think it really can be moved to the resolver because you'd need it in every root resolver right?

I agree that it should be an async throwing function.

**Comment by d-exclaimation** [comment]
I think it can be moved there, but yes, you will have to move it to all resolvers or at the very least add a method into the context that needed to be called to verify something like the JWT.

**Comment by d-exclaimation** [comment]
I added this feature in [v0.6.0](https://github.com/d-exclaimation/pioneer/releases/tag/0.6.0). If you have more to add, I'll reopen this issue

**Comment by cshadek** [comment]
That was fast!  Exactly what I needed.  Thanks!
