### ISSUE TITLE
How can I change the headers coming from GraphiQL?

### ISSUE THREAD

**Issue by cshadek** [d-exclaimation/pioneer#38]
My primary use case is to include an access token or user session token for a given user, but there could be other use cases.  Is this possible right now?

**Comment by cshadek** [comment]
I'm not entirely sure the best way to accomplish this.  There could be another parameter in the Pioneer init to include a list of headers, or maybe a specific parameter for adding a bearer token?  This would be immensely helpful to allow Pioneer to work in production.

**Comment by cshadek** [comment]
Actually it looks like some versions of GraphiQL have a way to add headers.  Would this be a better option?

https://stackoverflow.com/questions/69735713/how-to-enable-header-editor-enable-in-graphiql-rails-gem

**Comment by cshadek** [comment]
https://github.com/graphql/graphiql/pull/1543

**Comment by d-exclaimation** [comment]
Yeah, I didn't notice that, I remembered GraphiQL having one. In this [issue](https://github.com/graphql/graphiql/issues/2484), it said that older version of GraphiQL used to have the feature to add headers and that the current version have a bug that somehow removed it. I'll see what I can do beside waiting for that issue to be resolved.

In the mean time, if you don't have to specifically use GraphiQL, you could try using `.playground` and setting the websocket protocol to `.subscriptionTransportWs`

**Comment by cshadek** [comment]
It looks like GraphiQL might already support this.  Is this a simple change in the config.

https://github.com/graphql/graphiql/pull/1543

**Comment by cshadek** [comment]
It sounds like all we need to do is pass in the headerEditorEnabled prop

**Comment by d-exclaimation** [comment]
Yeah, I'll think I can update it now

**Comment by cshadek** [comment]
Awesome!

**Comment by d-exclaimation** [comment]
Not going to lie, it's a bit weird that it is disabled by default. Do let me know if there are more things like this.

**Comment by cshadek** [comment]
Yeah I agree it's a bit weird that's the default.  

Will do.  Thanks for being so quick to respond!  I'll recommend your library to my friends.
