### ISSUE TITLE
Can we support connectionParams for GraphiQL?

### ISSUE THREAD

**Issue by cshadek** [d-exclaimation/pioneer#40]
I've noticed using GraphiQL that the request headers are not being sent for subscriptions.  When I generate the Context I use the headers to get an access token, but the headers I defined within GraphiQL are not getting sent.  The headers do work for queries and mutations.

Is there a better alternative or is this a bug?

**Comment by cshadek** [comment]
I guess what I'm really asking is:  what is the best way to authenticate the user for subscriptions?

**Comment by cshadek** [comment]
https://www.apollographql.com/docs/apollo-server/data/subscriptions#onconnect-and-ondisconnect

**Comment by cshadek** [comment]
https://github.com/enisdenjo/graphql-ws/discussions/263

**Comment by cshadek** [comment]
https://github.com/enisdenjo/graphql-ws/discussions/263#discussioncomment-1612011

This seems like the way to do it.  I think all it involves is accepting a payload for ```ConnectionInit```.  That payload could then be passed to the contextBuilder as another parameter.  Then the contextBuilder could implement the logic to see if it was getting the parameters from the request or the connectionParams.

**Comment by d-exclaimation** [comment]
It's a bit more work to do that. I think I can still make the change though.

**Comment by d-exclaimation** [comment]
This is definitely a bug

**Comment by d-exclaimation** [comment]
The difficult part is that `connectionParams` is loosely typed and many examples just put whatever on it. I am not really liking the approach of adding another parameter to the `contextBuilder` because now you have to check for the `Request` and the additional payload to get a header for instance. Not to mention that in the subscriptions portion of the application, the request query is not present inside the `Request` object. I was considering having a seperate `contextBuilder` instead since now you will be provided with the payload, the query, and the arguments as well.

**Comment by d-exclaimation** [comment]
I have a somewhat of working solution with the seperate context builder but I have finals today so I'll make sure everything work properly and publish the new version later the day.

**Comment by cshadek** [comment]
Awesome!  I like that solution and I agree with you on your points

**Comment by d-exclaimation** [comment]
I couldn't find anything on GraphiQL that will let it pass the request header given in the header tab into the `connectionParams`, and whether that is even possible. 

This is websocket message sent by GraphiQL with some values in the header tab:
<img width="667" alt="Screenshot 2022-06-18 at 4 50 49 PM" src="https://user-images.githubusercontent.com/70748917/174432731-cf621349-dffc-416b-8212-5a6141b6b714.png">



I am aware of passing it manually shown https://github.com/graphql/graphiql/issues/2181#issuecomment-1046114322. However, I couldn't any resolution to passing the request header tab values as `connectionParams`.

I am personally using BananaCakePop which does sent the headers in the header tab into the `connectionParams` which verify that the changes made #41 does work.
<img width="1680" alt="Screenshot 2022-06-18 at 5 04 15 PM" src="https://user-images.githubusercontent.com/70748917/174432975-5220c737-9766-45aa-b871-588a5c142812.png">

However, it also have issues with not sending any other header with a key that is not the common header list.

**Comment by d-exclaimation** [comment]
I verified this does work with [Apollo Sandbox](https://studio.apollographql.com/sandbox/explorer), which was able to sent the request header specified in the header tab to the `connectionParams` which is received by the websocket context builder.

**Comment by d-exclaimation** [comment]
Technically, this library now properly support `connectionParams` in `graphql-ws` in [0.7.0](https://github.com/d-exclaimation/pioneer/releases/tag/0.7.0), but since your original question involved GraphiQL which is not capable to pass the request header into the `connectionParams`, I will keep this issue open until I can resolve that issue.

**Comment by cshadek** [comment]
Thanks for doing this so quickly!  I guess I'm using Apollo Sandbox for now

**Comment by d-exclaimation** [comment]
### Update 

- #43 

Latest version of `@apollo/sandbox` now have supported subscriptions and seemed to meet feature parity with the cloud hosted version. 

Whether there are still some issue with the self hosted one, I am not too sure. I will be spending some time looking into this and possibly update this library to have that as its default GraphQL IDE

**Comment by d-exclaimation** [comment]
### Update

 - graphql/graphiql#2181

Latest version of `graphiql` also now pass request headers as `connectionParams` . Although, I have to check whether everything work properly with the way it is setup.

In terms of default option for playground, both seemed like good choices now. I am considering Apollo Sandbox as the default option if both are working well. I will be closing this issue after I checked and fixed any issue with both IDEs

**Comment by d-exclaimation** [comment]
> ### Update
> 
> 
> 
>  - graphql/graphiql#2181
> 
> 
> 
> Latest version of `graphiql` also now pass request headers as `connectionParams` . Although, I have to check whether everything work properly with the way it is setup.
> 
> 
> 
> In terms of default option for playground, both seemed like good choices now. I am considering Apollo Sandbox as the default option if both are working well. I will be closing this issue after I checked and fixed any issue with both IDEs

GraphiQL can send `connectionParams` for `graphql-ws` but not for `subscriptions-transport-ws`. To be fair, this is a non issue as `subscriptions-transport-ws` is considered legacy now, but this also meant the default IDE is likely going to be Apollo Sandbox instead of GraphiQL.

**Comment by d-exclaimation** [comment]
The default is changed now. Made sure both Apollo Sandbox and GraphiQL should be working properly using the latest version in [v0.10.1](https://github.com/d-exclaimation/pioneer/releases/tag/0.10.1).

Closing this issue for now, feel free to reopen an issue related come up
