### ISSUE TITLE
Apollo Sandbox Self-Hosted Option

### ISSUE THREAD

**Issue by cshadek** [d-exclaimation/pioneer#43]
Apollo Sandbox now allows you to embed Apollo Sandbox on your own website and localhost.  This could be a nice option to add support for this and it may prevent needing to make CORS changes.  I would imagine it would be a similar process to how GraphiQL and the localhost version of BananaCakePop are hosted.

https://www.apollographql.com/blog/tooling/graphql-ide/how-to-use-apollo-sandbox-on-your-localhost/

**Comment by d-exclaimation** [comment]
I was thinking of implementing this as well. I was aware that embeddable Apollo Studio Explorer is a thing, but the regular Apollo Studio Explorer require an account, so I didn't do anything about it. I wasn't aware that the Sandbox version is also embeddable.


I'll definitely look into it.

**Comment by d-exclaimation** [comment]
I tried the embedded sandbox and it does work well (no account needed), but you can't run subscription operations as it is unsupported on embedded sandbox, which is a big downside compared to the other IDE.

<img width="367" alt="Screenshot 2022-06-20 at 4 35 23 AM" src="https://user-images.githubusercontent.com/70748917/174501236-36dbfaf8-518e-4552-9250-d2c6965ab430.png">

**Comment by cshadek** [comment]
Oh I didn't realize that.  That's a big downside.  Maybe this is something better for the future?  I'm sure they'll add support eventually.

**Comment by d-exclaimation** [comment]
I'll probably going to still add it in, but it won't replace the redirect option until they add support for subscriptions in embedded sandbox.

**Comment by cshadek** [comment]
Sounds like a plan.

**Comment by d-exclaimation** [comment]
The option for embedded sandbox should be available in [`v0.7.1`](https://github.com/d-exclaimation/pioneer/releases/tag/0.7.1)
