### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by ZirgVoice** [d-exclaimation/pioneer#54]
Graphiti has Connection for adding pagination, can it be used somehow with QueryBuilder?

**Comment by ZirgVoice** [comment]
My question is how to get items from database with cursor pagination. The example describes array-based pagination, but we do not get the entire array of data from the database, but only a part corresponding to the specified limit.

**Comment by d-exclaimation** [comment]
I don't think that feature belongs here.

This library does not and should not dictate nor restrict how you would describe your schema, how you would resolve them, and what datastore is used.
