### ISSUE TITLE
AbortError headers are ignored

### ISSUE THREAD

**Issue by d-exclaimation** [d-exclaimation/pioneer#71]
**Describe the bug**
When an `AbortError` is thrown at any point of the code the `headers` values are always ignored, and thus meant nothing.

**To Reproduce**
1. Create any Schema
2. Create a context builder that always throws an `Abort` or any `AbortError` with some `headers` 
3. Create and Run Pioneer GraphQL server
3. Query any field so the context builder is executed
4. See that no new headers are set in the response 

**Expected behavior**
Expected that the `headers` is set to the response headers.

**Desktop (please complete the following information):**
 - OS: macOS v12 or up
 - Version 0.8.6
 - Any Pioneer configuration

**Comment by d-exclaimation** [comment]
Planning to patch this soon, but waiting for validation rules (GraphQLSwift/GraphQL#99) and the fixed `ConcurrentEventStream` 
(GraphQLSwift/GraphQL#102) PRs to be merged and a new version of [GraphQLSwift/GraphQL](https://github.com/GraphQLSwift/GraphQL) to be released.

**Comment by NeedleInAJayStack** [comment]
@d-exclaimation Cool, those MRs have been merged and tagged! Thanks for contributing!
